export interface StaticProduct {
  id: string;
  name: string;
  slug: string;
  tagline: string;
  description: string;
  price: number;
  compareAtPrice: number | null;
  imageUrls: string[];
  stock: number;
  isFeatured: number;
  topNotes: string;
  heartNotes: string;
  baseNotes: string;
  tags: string;
}

export interface StaticVariant {
  id: string;
  productId: string;
  size: string;
  price: number;
  stock: number;
}

export const staticProducts: StaticProduct[] = [
  {
    id: 'prod-silver-birch',
    name: 'Silver Birch',
    slug: 'silver-birch',
    tagline: '50ml EDT',
    description: 'Crisp, clean woody scent, fresh like birch bark in the cold.',
    price: 4700,
    compareAtPrice: null,
    imageUrls: ['/images/silver_birch.jpg'],
    stock: 45,
    isFeatured: 1,
    topNotes: 'Pine Needles, White Iris',
    heartNotes: 'Birch Wood, Cedarwood, Juniper',
    baseNotes: 'Earthy Vetiver, Oakmoss, Patchouli',
    tags: 'Woody, Fresh, Unisex, New Arrival',
  },
  {
    id: 'prod-rose-gold-oud',
    name: 'Rose Gold Oud',
    slug: 'rose-gold-oud',
    tagline: '30ml EDT',
    description: 'Warm rose paired with smoky, luxurious oud.',
    price: 5400,
    compareAtPrice: 6500,
    imageUrls: ['/images/rose_gold_oud_1.jpg', '/images/rose_gold_oud_2.jpg', '/images/rose_gold_oud_3.jpg'],
    stock: 30,
    isFeatured: 1,
    topNotes: 'Saffron, Pink Pepper, Red Berries',
    heartNotes: 'Damask Rose, Jasmine, Praline',
    baseNotes: 'Oud Wood, Frankincense, Vanilla, Amber',
    tags: 'Floral, Oud, Spicy, Unisex, Bestseller',
  },
  {
    id: 'prod-pure-jasmine',
    name: 'Pure Jasmine',
    slug: 'pure-jasmine',
    tagline: '50ml EDP',
    description: 'Soft, delicate white floral, pure and romantic.',
    price: 4500,
    compareAtPrice: null,
    imageUrls: ['/images/pure_jasmine.jpg'],
    stock: 40,
    isFeatured: 0,
    topNotes: 'Jasmine Sambac, Bergamot, Green Leaves',
    heartNotes: 'Star Jasmine, Orange Blossom, Lily',
    baseNotes: 'Clean White Musk, Soft Sandalwood',
    tags: 'Floral, Clean, Unisex',
  },
  {
    id: 'prod-morning-dew',
    name: 'Morning Dew',
    slug: 'morning-dew',
    tagline: '30ml EDT',
    description: 'Light, green, dewy freshness — like an early morning walk.',
    price: 4600,
    compareAtPrice: null,
    imageUrls: ['/images/morning_dew.jpg'],
    stock: 40,
    isFeatured: 0,
    topNotes: 'Bergamot, Lime Peel, Morning Dew Accord',
    heartNotes: 'Wet Moss, Lichen, Green Ivy',
    baseNotes: 'Sandalwood, White Musk, Patchouli',
    tags: 'Fresh, Green, Unisex',
  },
  {
    id: 'prod-white-freesia',
    name: 'White Freesia',
    slug: 'white-freesia',
    tagline: '50ml EDT',
    description: 'Clean, soft, powdery floral scent.',
    price: 5500,
    compareAtPrice: null,
    imageUrls: ['/images/white_freesia.jpg'],
    stock: 25,
    isFeatured: 0,
    topNotes: 'White Freesia, Pear Blossom, Aldehydes',
    heartNotes: 'Lily of the Valley, Jasmine, Peony',
    baseNotes: 'White Musk, Sandalwood, Cashmere Wood',
    tags: 'Floral, Fresh, Powdery, Unisex',
  },
  {
    id: 'prod-bergamot-breeze',
    name: 'Bergamot Breeze',
    slug: 'bergamot-breeze',
    tagline: '30ml EDT',
    description: 'Zesty citrus bergamot, bright and airy.',
    price: 4400,
    compareAtPrice: null,
    imageUrls: ['/images/bergamot_breeze.jpg'],
    stock: 45,
    isFeatured: 0,
    topNotes: 'Bergamot Peel, Lime Leaf, Grapefruit',
    heartNotes: 'Neroli, Green Tea, Jasmine',
    baseNotes: 'White Musk, Cedarwood, Vetiver',
    tags: 'Citrus, Fresh, Clean, Unisex',
  },
  {
    id: 'prod-sparkling-citrus',
    name: 'Sparkling Citrus',
    slug: 'sparkling-citrus',
    tagline: '30ml EDT',
    description: 'Juicy orange burst, energizing and fresh.',
    price: 4300,
    compareAtPrice: null,
    imageUrls: ['/images/sparkling_citrus.jpg'],
    stock: 55,
    isFeatured: 0,
    topNotes: 'Juicy Orange, Mandarin Peel, Tangerine',
    heartNotes: 'Grapefruit, Orange Blossom, Verbena',
    baseNotes: 'White Honey, Cedarwood, Musk',
    tags: 'Citrus, Fresh, Unisex',
  },
  {
    id: 'prod-honey-blossom',
    name: 'Honey Blossom',
    slug: 'honey-blossom',
    tagline: '30ml EDT',
    description: 'Sweet golden honey with a soft floral touch.',
    price: 5300,
    compareAtPrice: 6300,
    imageUrls: ['/images/honey_blossom.jpg'],
    stock: 30,
    isFeatured: 0,
    topNotes: 'Orange Blossom, Lemon Nectar',
    heartNotes: 'Raw Honeycomb, White Rose, Beeswax',
    baseNotes: 'Golden Amber, Vanilla Pod, Cedarwood',
    tags: 'Floral, Amber, Sweet, Unisex',
  },
  {
    id: 'prod-sweet-lychee',
    name: 'Sweet Lychee',
    slug: 'sweet-lychee',
    tagline: 'EDT',
    description: 'Playful, sweet, fruity lychee aroma.',
    price: 5200,
    compareAtPrice: null,
    imageUrls: ['/images/sweet_lychee.jpg'],
    stock: 25,
    isFeatured: 0,
    topNotes: 'Sweet Lychee, Red Currant, Pear',
    heartNotes: 'Pink Rose, Freesia, Lily of the Valley',
    baseNotes: 'Clean Linen Accord, White Musk, Sandalwood',
    tags: 'Floral, Fresh, Unisex',
  },
  {
    id: 'prod-white-tea-thyme',
    name: 'White Tea & Thyme',
    slug: 'white-tea-thyme',
    tagline: '30ml EDT',
    description: 'Calm herbal-green blend of tea leaves and thyme.',
    price: 4300,
    compareAtPrice: null,
    imageUrls: ['/images/white_tea_thyme.jpg'],
    stock: 50,
    isFeatured: 0,
    topNotes: 'White Tea, Bergamot, Coriander',
    heartNotes: 'Thyme, Sage, White Rose',
    baseNotes: 'White Musk, Cedarwood, Amber',
    tags: 'Fresh, Green, Tea, Unisex',
  },
  {
    id: 'prod-alpine-air',
    name: 'Alpine Air',
    slug: 'alpine-air',
    tagline: '50ml EDT',
    description: 'Cool, crisp mountain freshness.',
    price: 5200,
    compareAtPrice: 6200,
    imageUrls: ['/images/alpine_air.jpg'],
    stock: 25,
    isFeatured: 0,
    topNotes: 'Glacial Accord, Crisp Oxygen, Mint Leaf',
    heartNotes: 'Snow Blossom, Juniper, Pine needles',
    baseNotes: 'Frozen Cedar, Oakmoss, Clean Musk',
    tags: 'Fresh, Marine, Unisex',
  },
  {
    id: 'prod-clean-cotton',
    name: 'Clean Cotton',
    slug: 'clean-cotton',
    tagline: '50ml EDT',
    description: 'Soft, freshly-laundered linen scent.',
    price: 5100,
    compareAtPrice: null,
    imageUrls: ['/images/clean_cotton.jpg'],
    stock: 35,
    isFeatured: 0,
    topNotes: 'Powdery Aldehydes, White Lily, Clean Air',
    heartNotes: 'Cotton Blossom, Violet Leaf, White Rose',
    baseNotes: 'Pure White Musk, Sandalwood, Soft Amber',
    tags: 'Clean, Powdery, Unisex',
  },
  {
    id: 'prod-bamboo-mist',
    name: 'Bamboo Mist',
    slug: 'bamboo-mist',
    tagline: '50ml EDT',
    description: 'Light, spa-like green bamboo freshness.',
    price: 4500,
    compareAtPrice: null,
    imageUrls: ['/images/bamboo_mist.jpg'],
    stock: 40,
    isFeatured: 0,
    topNotes: 'Green Bamboo, Cucumber Water, Dewy Grass',
    heartNotes: 'Green Tea, Lotus Petals, White Lily',
    baseNotes: 'Soft Woods, Clean Musk, Vetiver',
    tags: 'Fresh, Green, Unisex',
  },
  {
    id: 'prod-hibiscus-sky',
    name: 'Hibiscus Sky',
    slug: 'hibiscus-sky',
    tagline: '30ml EDT',
    description: 'Warm tropical floral with a sunset glow.',
    price: 4600,
    compareAtPrice: null,
    imageUrls: ['/images/hibiscus_sky.jpg'],
    stock: 40,
    isFeatured: 0,
    topNotes: 'Hibiscus, Mandarin, Red Berries',
    heartNotes: 'Plumeria, Coconut Water, White Rose',
    baseNotes: 'Solar Amber, Vanilla Pod, Soft Musk',
    tags: 'Floral, Amber, Unisex',
  },
  {
    id: 'prod-pear-sorbet',
    name: 'Pear Sorbet',
    slug: 'pear-sorbet',
    tagline: '30ml EDT',
    description: 'Cool, sweet, fruity pear freshness.',
    price: 5100,
    compareAtPrice: null,
    imageUrls: ['/images/pear_sorbet.jpg'],
    stock: 20,
    isFeatured: 0,
    topNotes: 'Frosted Pear, Lime Zest, Mint Leaf',
    heartNotes: 'Green Apple, Melon, Freesia',
    baseNotes: 'White Musk, Cedarwood, Ice Accord',
    tags: 'Fresh, Fruit, Unisex',
  },
  {
    id: 'prod-wild-bluebell',
    name: 'Wild Bluebell',
    slug: 'wild-bluebell',
    tagline: '50ml EDP',
    description: 'Soft wildflower floral, gentle and sweet.',
    price: 4800,
    compareAtPrice: 5800,
    imageUrls: ['/images/wild_bluebell.jpg'],
    stock: 35,
    isFeatured: 0,
    topNotes: 'Bluebell, Clove, Dewy Green Accord',
    heartNotes: 'Lily of the Valley, Jasmine, Persimmon',
    baseNotes: 'Powdery Musk, White Amber, Light Wood',
    tags: 'Floral, Fresh, Unisex',
  },
  {
    id: 'prod-apricot-nectar',
    name: 'Apricot Nectar',
    slug: 'apricot-nectar',
    tagline: '50ml EDT',
    description: 'Juicy, sun-ripened apricot warmth.',
    price: 5800,
    compareAtPrice: 6800,
    imageUrls: ['/images/apricot_nectar.jpg'],
    stock: 30,
    isFeatured: 0,
    topNotes: 'Ripe Apricot, Mandarin Nectar, Peach',
    heartNotes: 'Apricot Blossom, Freesia, Rosewater',
    baseNotes: 'Bourbon Vanilla, Cashmere Wood, Soft Musk',
    tags: 'Gourmand, Fruit, Unisex',
  },
  {
    id: 'prod-sunny-mimosa',
    name: 'Sunny Mimosa',
    slug: 'sunny-mimosa',
    tagline: '50ml EDT',
    description: 'Bright, sunny golden mimosa florals.',
    price: 5100,
    compareAtPrice: 6200,
    imageUrls: ['/images/sunny_mimosa.jpg'],
    stock: 30,
    isFeatured: 0,
    topNotes: 'Yellow Mimosa, Cardamom, Bergamot',
    heartNotes: 'Black Tea, Honey Blossom, Violet Leaf',
    baseNotes: 'Flaky Pastry Accord, White Musk, Sandalwood',
    tags: 'Floral, Gourmand, Unisex',
  },
  {
    id: 'prod-cherry-blossom',
    name: 'Cherry Blossom',
    slug: 'cherry-blossom',
    tagline: '30ml EDT',
    description: 'Delicate, romantic pink floral.',
    price: 5200,
    compareAtPrice: null,
    imageUrls: ['/images/cherry_blossom.jpg'],
    stock: 30,
    isFeatured: 0,
    topNotes: 'Cherry Blossom, Sakura Petals, Bergamot',
    heartNotes: 'White Jasmine, Rosewater, Sweet Pear',
    baseNotes: 'White Musk, Sandalwood, Cashmere Wood',
    tags: 'Floral, Powdery, Unisex',
  },
  {
    id: 'prod-citrus-zest',
    name: 'Citrus Zest',
    slug: 'citrus-zest',
    tagline: '30ml EDT',
    description: 'Bright, zesty bergamot and lemon, a true citrus burst.',
    price: 4200,
    compareAtPrice: 5200,
    imageUrls: ['/images/citrus_zest.jpg'],
    stock: 45,
    isFeatured: 1,
    topNotes: 'Amalfi Lemon, Bergamot, Grapefruit',
    heartNotes: 'Orange Blossom, Lime Leaf, Mint',
    baseNotes: 'White Honey, Cedarwood, Musk',
    tags: 'Citrus, Fresh, Unisex, Bestseller',
  },
  {
    id: 'prod-midnight-jasmine',
    name: 'Midnight Jasmine',
    slug: 'midnight-jasmine',
    tagline: 'EDT',
    description: 'Deep, sensual jasmine that blooms at night.',
    price: 4700,
    compareAtPrice: null,
    imageUrls: ['/images/midnight_jasmine.jpg'],
    stock: 40,
    isFeatured: 0,
    topNotes: 'Black Pepper, Clove, Morning Dew',
    heartNotes: 'Night-Blooming Jasmine, White Lily, Ylang-Ylang',
    baseNotes: 'Balsamic Incense, Madagascar Vanilla, Sandalwood',
    tags: 'Floral, Warm, Incense, Unisex',
  },
  {
    id: 'prod-sandalwood-sun',
    name: 'Sandalwood Sun',
    slug: 'sandalwood-sun',
    tagline: '50ml EDT',
    description: 'Warm, creamy sandalwood with a sun-baked glow.',
    price: 4900,
    compareAtPrice: 5900,
    imageUrls: ['/images/sandalwood_sun.jpg'],
    stock: 35,
    isFeatured: 0,
    topNotes: 'Cardamom, Saffron, Bergamot',
    heartNotes: 'Mysore Sandalwood, Cashmere Wood, Warm Sand',
    baseNotes: 'Golden Amber, Cedarwood, Vanilla',
    tags: 'Woody, Amber, Spicy, Unisex',
  },
  {
    id: 'prod-golden-patchouli',
    name: 'Golden Patchouli',
    slug: 'golden-patchouli',
    tagline: '50ml EDT',
    description: 'Rich, earthy patchouli with a warm amber depth.',
    price: 5000,
    compareAtPrice: 6000,
    imageUrls: ['/images/golden_patchouli.jpg'],
    stock: 35,
    isFeatured: 0,
    topNotes: 'Cardamom, Clove, Orange Peel',
    heartNotes: 'Golden Patchouli, Warm Wax, Dry Leaves',
    baseNotes: 'Oak Wood, Amber, Vetiver',
    tags: 'Woody, Earthy, Amber, Unisex',
  },
  {
    id: 'prod-lavender-fields',
    name: 'Lavender Fields',
    slug: 'lavender-fields',
    tagline: '50ml EDP',
    description: 'Calming, herbal lavender straight from the field.',
    price: 4400,
    compareAtPrice: null,
    imageUrls: ['/images/lavender_fields.jpg'],
    stock: 45,
    isFeatured: 0,
    topNotes: 'Wild Lavender, Bergamot, Sage',
    heartNotes: 'Iris, Violet, White Honey',
    baseNotes: 'Cashmere Wood, Powdery Musk, Amber',
    tags: 'Floral, Clean, Powdery, Unisex',
  },
  {
    id: 'prod-oceanic-breeze',
    name: 'Oceanic Breeze',
    slug: 'oceanic-breeze',
    tagline: '50ml EDT',
    description: 'Fresh, salty sea-air scent, cool and invigorating.',
    price: 4500,
    compareAtPrice: null,
    imageUrls: ['/images/oceanic_breeze.jpg'],
    stock: 45,
    isFeatured: 0,
    topNotes: 'Sea Salt, Ozone, Bergamot',
    heartNotes: 'Water Lily, Kelp, Rosemary',
    baseNotes: 'Wet Stones, Oakmoss, Ambergris',
    tags: 'Fresh, Marine, Unisex',
  },
  {
    id: 'prod-emerald-vetiver',
    name: 'Emerald Vetiver',
    slug: 'emerald-vetiver',
    tagline: 'EDT',
    description: 'Deep, earthy green vetiver, grounded and woody.',
    price: 4800,
    compareAtPrice: null,
    imageUrls: ['/images/emerald_vetiver.jpg'],
    stock: 35,
    isFeatured: 0,
    topNotes: 'Forest Mist Accord, Grapefruit, Galbanum',
    heartNotes: 'Green Fern, Juniper, Coriander',
    baseNotes: 'Smoked Vetiver, Oakmoss, Patchouli',
    tags: 'Woody, Earthy, Unisex',
  },
  {
    id: 'prod-velvet-orchid',
    name: 'Velvet Orchid',
    slug: 'velvet-orchid',
    tagline: '30ml EDP',
    description: 'Rich, plush floral with a dark, luxurious edge.',
    price: 5200,
    compareAtPrice: 6500,
    imageUrls: ['/images/velvet_orchid.jpg'],
    stock: 25,
    isFeatured: 0,
    topNotes: 'Black Cherry, Pink Pepper, Rum Accord',
    heartNotes: 'Velvet Orchid, White Jasmine, Gardenia',
    baseNotes: 'Madagascar Vanilla, Amber, Sandalwood',
    tags: 'Floral, Amber, Sweet, Unisex',
  },
  {
    id: 'prod-sapphire-mint',
    name: 'Sapphire Mint',
    slug: 'sapphire-mint',
    tagline: '50ml EDT',
    description: 'Icy-cool mint with a crisp, refreshing chill.',
    price: 4100,
    compareAtPrice: null,
    imageUrls: ['/images/sapphire_mint.jpg'],
    stock: 55,
    isFeatured: 0,
    topNotes: 'Wild Peppermint, Spearmint, Icy Ozone',
    heartNotes: 'Green Tea, Eucalyptus, Sage',
    baseNotes: 'Cedarwood, Frost Accord, White Musk',
    tags: 'Fresh, Green, Unisex',
  },
  {
    id: 'prod-cedarwood-peak',
    name: 'Cedarwood Peak',
    slug: 'cedarwood-peak',
    tagline: '30ml EDT',
    description: 'Rugged, dry cedarwood with mountain-air freshness.',
    price: 4900,
    compareAtPrice: 6200,
    imageUrls: ['/images/cedarwood_peak.jpg'],
    stock: 30,
    isFeatured: 0,
    topNotes: 'Alpine Accord, Pine Needles, Bergamot',
    heartNotes: 'Atlas Cedarwood, Cypress, Juniper',
    baseNotes: 'Oakmoss, Patchouli, Dry Wood',
    tags: 'Woody, Fresh, Unisex',
  },
  {
    id: 'prod-peony-silk',
    name: 'Peony Silk',
    slug: 'peony-silk',
    tagline: 'EDT',
    description: 'Soft, silky peony floral, light and elegant.',
    price: 4950,
    compareAtPrice: null,
    imageUrls: ['/images/peony_silk.jpg'],
    stock: 35,
    isFeatured: 0,
    topNotes: 'Pink Peony, Morning Dew, Mandora',
    heartNotes: 'White Rose, Powdery Iris, Silk Accord',
    baseNotes: 'White Honey, Cashmere Wood, Soft Musk',
    tags: 'Floral, Powdery, Unisex',
  }
];

export function getStaticVariants(productId: string): StaticVariant[] {
  const prod = staticProducts.find(p => p.id === productId);
  if (!prod) return [];
  
  // Standard prices scaled by size
  const price30 = Math.round(prod.price * 0.85);
  const price50 = prod.price;
  const price100 = Math.round(prod.price * 1.5);
  
  return [
    { id: `${productId}-30ml`, productId, size: '30ml', price: price30, stock: prod.stock },
    { id: `${productId}-50ml`, productId, size: '50ml', price: price50, stock: prod.stock },
    { id: `${productId}-100ml`, productId, size: '100ml', price: price100, stock: prod.stock }
  ];
}
