name = "vn-aroma"
compatibility_date = "2024-01-01"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output"

[[d1_databases]]
binding = "DB"
database_name = "vn-aroma-db"
database_id = "ce486519-79d2-418b-84eb-e342a073d4d3"
migrations_dir = "./drizzle"
