name = "vn-aroma"
compatibility_date = "2024-01-01"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "vn-aroma-db"
database_id = "140abc4c-c838-4bac-8ed5-7ffcfcd63c83"
migrations_dir = "./drizzle"
