import { NextResponse } from 'next/server';
import { getDb } from '@/db';
import { users, products, variants } from '@/db/schema';
import { eq } from 'drizzle-orm';

export const runtime = 'edge';
export const dynamic = 'force-dynamic';

// Web Crypto PBKDF2 Password Hashing Helper
async function hashPassword(password: string): Promise<string> {
  const encoder = new TextEncoder();
  const passwordBuffer = encoder.encode(password);
  const salt = crypto.getRandomValues(new Uint8Array(16));

  const baseKey = await crypto.subtle.importKey(
    'raw',
    passwordBuffer,
    { name: 'PBKDF2' },
    false,
    ['deriveBits', 'deriveKey']
  );

  const derivedKeyBits = await crypto.subtle.deriveBits(
    {
      name: 'PBKDF2',
      salt: salt,
      iterations: 100000,
      hash: 'SHA-256'
    },
    baseKey,
    256
  );

  const saltHex = Array.from(salt).map(b => b.toString(16).padStart(2, '0')).join('');
  const keyHex = Array.from(new Uint8Array(derivedKeyBits)).map(b => b.toString(16).padStart(2, '0')).join('');

  return `${saltHex}:${keyHex}`;
}

export async function GET() {
  try {
    const db = getDb();

    // 1. Create tables if they do not exist
    const createTableQueries = [
      `CREATE TABLE IF NOT EXISTS users (
        id TEXT PRIMARY KEY,
        email TEXT UNIQUE NOT NULL,
        password_hash TEXT NOT NULL,
        name TEXT NOT NULL,
        role TEXT NOT NULL DEFAULT 'user',
        created_at INTEGER NOT NULL
      );`,
      `CREATE TABLE IF NOT EXISTS products (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        slug TEXT UNIQUE NOT NULL,
        tagline TEXT NOT NULL,
        description TEXT NOT NULL,
        price INTEGER NOT NULL,
        compare_at_price INTEGER,
        image_urls TEXT NOT NULL,
        stock INTEGER NOT NULL DEFAULT 0,
        is_featured INTEGER NOT NULL DEFAULT 0,
        top_notes TEXT NOT NULL,
        heart_notes TEXT NOT NULL,
        base_notes TEXT NOT NULL,
        tags TEXT NOT NULL,
        created_at INTEGER NOT NULL
      );`,
      `CREATE TABLE IF NOT EXISTS variants (
        id TEXT PRIMARY KEY,
        product_id TEXT NOT NULL,
        size TEXT NOT NULL,
        price INTEGER NOT NULL,
        stock INTEGER NOT NULL DEFAULT 0,
        FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE
      );`,
      `CREATE TABLE IF NOT EXISTS orders (
        id TEXT PRIMARY KEY,
        user_id TEXT,
        order_number TEXT UNIQUE NOT NULL,
        total_amount INTEGER NOT NULL,
        shipping_address TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'Processing',
        payment_status TEXT NOT NULL DEFAULT 'Pending',
        razorpay_order_id TEXT,
        razorpay_payment_id TEXT,
        created_at INTEGER NOT NULL,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
      );`,
      `CREATE TABLE IF NOT EXISTS order_items (
        id TEXT PRIMARY KEY,
        order_id TEXT NOT NULL,
        product_id TEXT NOT NULL,
        variant_id TEXT,
        quantity INTEGER NOT NULL,
        price_at_purchase INTEGER NOT NULL,
        size TEXT NOT NULL,
        FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,
        FOREIGN KEY(product_id) REFERENCES products(id)
      );`,
      `CREATE TABLE IF NOT EXISTS cart_items (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        product_id TEXT NOT NULL,
        variant_id TEXT,
        quantity INTEGER NOT NULL DEFAULT 1,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
        FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE
      );`
    ];

    for (const query of createTableQueries) {
      await db.run(query);
    }

    // 2. Clear existing seed data to ensure fresh seed
    await db.delete(variants);
    await db.delete(products);

    // 3. Create Admin User if not exists
    const adminEmail = 'admin@vnaroma.com';
    const existingAdmin = await db.select().from(users).where(eq(users.email, adminEmail)).get();
    
    if (!existingAdmin) {
      const hashedAdminPassword = await hashPassword('admin123');
      await db.insert(users).values({
        id: crypto.randomUUID(),
        email: adminEmail,
        passwordHash: hashedAdminPassword,
        name: 'VN Aroma Admin',
        role: 'admin',
        createdAt: Math.floor(Date.now() / 1000),
      });
    }

    // 4. 35 Luxury Perfumes Dataset
    const perfumesData = [
      {
        id: 'prod-lune-bleue',
        name: 'Lune Bleue',
        slug: 'lune-bleue',
        tagline: 'Citrus, sea salt, and whispers of moonlight.',
        description: 'A luminous and fresh fragrance inspired by cool ocean breezes under a full moon. Bright grapefruit and sea salt open into a heart of mineral sage, grounded by dark cedarwood and soft musk. Clean, marine, and elegant.',
        price: 4500,
        compareAtPrice: 5500,
        imageUrls: JSON.stringify(['/images/lune_bleue.jpg', '/images/trio.png']),
        stock: 50,
        isFeatured: 1,
        topNotes: 'Bergamot, Grapefruit, Sea Accord',
        heartNotes: 'Sea Salt, Sage, Rosemary',
        baseNotes: 'Cedarwood, Ambergris, Musk',
        tags: 'Fresh, Marine, Unisex, Bestseller',
      },
      {
        id: 'prod-epice-noire',
        name: 'Épice Noire',
        slug: 'epice-noire',
        tagline: 'Warm amber, black pepper, and sacred woods.',
        description: 'A rich, seductive, and complex fragrance that captures the warmth of oriental spices. Bold black pepper and aromatic cardamom fuse with cinnamon and cloves, resting on a base of creamy sandalwood and rich amber.',
        price: 4800,
        compareAtPrice: 5800,
        imageUrls: JSON.stringify(['/images/epice_noire.jpg', '/images/trio.png']),
        stock: 40,
        isFeatured: 1,
        topNotes: 'Black Pepper, Cardamom, Bergamot',
        heartNotes: 'Cinnamon, Clove, Nutmeg',
        baseNotes: 'Sandalwood, Patchouli, Amber, Vanilla',
        tags: 'Spicy, Amber, Woody, Unisex, Bestseller',
      },
      {
        id: 'prod-inhale',
        name: 'Inhale',
        slug: 'inhale',
        tagline: 'Soft rose, lychee, and fresh linen.',
        description: 'A clean, soft, and powdery floral fragrance that evokes the purity of morning light and fresh linen. Crisp pear and sweet lychee lead to a heart of blooming rose and peony, ending in a warm cashmere wood embrace.',
        price: 4600,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/inhale.jpg', '/images/trio.png']),
        stock: 60,
        isFeatured: 1,
        topNotes: 'Pear, Lychee, Aldehydes',
        heartNotes: 'Damask Rose, Peony, Freesia',
        baseNotes: 'White Musk, Sandalwood, Cashmere Wood',
        tags: 'Floral, Clean, Powdery, Unisex, New Arrival',
      },
      {
        id: 'prod-citrus-zest',
        name: 'Citrus Zest',
        slug: 'citrus-zest',
        tagline: 'Bright mandarin peel, Sicilian lemon, and green verbena.',
        description: 'An energizing, sun-kissed citrus blast that captures the crisp air of Amalfi. Lush lemon verbena and fresh bergamot open into orange blossom, resting on white honey and clean cedar wood.',
        price: 4200,
        compareAtPrice: 5200,
        imageUrls: JSON.stringify(['/images/citrus_zest.jpg', '/images/trio.png']),
        stock: 45,
        isFeatured: 1,
        topNotes: 'Amalfi Lemon, Bergamot, Grapefruit',
        heartNotes: 'Orange Blossom, Lime Leaf, Mint',
        baseNotes: 'White Honey, Cedarwood, Musk',
        tags: 'Citrus, Fresh, Unisex, Bestseller',
      },
      {
        id: 'prod-silver-birch',
        name: 'Silver Birch',
        slug: 'silver-birch',
        tagline: 'Earthy wood, birch bark, and crisp winter air.',
        description: 'A clean, mineral, wood-centric fragrance that feels like walking through a damp birch forest in early winter. Fresh silver leaf pine opens into birch bark, grounded by rich vetiver and patchouli.',
        price: 4700,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/silver_birch.jpg', '/images/trio.png']),
        stock: 35,
        isFeatured: 1,
        topNotes: 'Pine Needles, White Iris',
        heartNotes: 'Birch Wood, Cedarwood, Juniper',
        baseNotes: 'Earthy Vetiver, Oakmoss, Patchouli',
        tags: 'Woody, Fresh, Unisex, New Arrival',
      },
      {
        id: 'prod-rose-gold-oud',
        name: 'Rose Gold Oud',
        slug: 'rose-gold-oud',
        tagline: 'Turkish rose absolute, saffron, and golden incense.',
        description: 'A dramatic, opulent, oriental floral masterpiece. Precious Damask Rose is wrapped in warm saffron and gold resin incense, resting on a base of rich Cambodian oud and bourbon vanilla.',
        price: 5400,
        compareAtPrice: 6500,
        imageUrls: JSON.stringify(['/images/rose_gold_oud_1.jpg', '/images/rose_gold_oud_2.jpg']),
        stock: 30,
        isFeatured: 1,
        topNotes: 'Saffron, Pink Pepper, Red Berries',
        heartNotes: 'Damask Rose, Jasmine, Praline',
        baseNotes: 'Oud Wood, Frankincense, Vanilla, Amber',
        tags: 'Floral, Oud, Spicy, Unisex, Bestseller',
      },
      {
        id: 'prod-bois-sacre',
        name: 'Bois Sacré',
        slug: 'bois-sacre',
        tagline: 'Smoky incense, cedarwood, and gold resin.',
        description: 'An elegant, meditative woody fragrance. Rich incense smoke and dried spices blend into deep cedarwood and vetiver, creating an aura of sacred silence and dry warmth.',
        price: 4900,
        compareAtPrice: 6200,
        imageUrls: JSON.stringify(['/images/epice_noire.jpg', '/images/trio.png']),
        stock: 30,
        isFeatured: 0,
        topNotes: 'Frankincense, Pink Pepper',
        heartNotes: 'Cedarwood, Atlas Cedar, Cypress',
        baseNotes: 'Vetiver, Sandalwood, Amber',
        tags: 'Woody, Incense, Warm, Unisex',
      },
      {
        id: 'prod-ombre-rose',
        name: 'Ombre Rose',
        slug: 'ombre-rose',
        tagline: 'Velvety rose, dark oud, and sweet saffron.',
        description: 'A dramatic, dark floral masterpiece. Velvety Turkish rose is wrapped in the smoky shadows of precious oud and precious saffron, with a rich hint of dark praline and vanilla.',
        price: 5200,
        compareAtPrice: 6500,
        imageUrls: JSON.stringify(['/images/inhale.jpg', '/images/trio.png']),
        stock: 25,
        isFeatured: 0,
        topNotes: 'Saffron, Clove, Red Fruits',
        heartNotes: 'Damask Rose, Rose Absolute, Jasmine',
        baseNotes: 'Oud, Praline, Vanilla, Amber',
        tags: 'Floral, Oud, Sweet, Unisex',
      },
      {
        id: 'prod-eau-fraiche',
        name: 'Eau Fraîche',
        slug: 'eau-fraiche',
        tagline: 'Crushed mint, verbena, and botanical dew.',
        description: 'An energizing, green citrus scent that feels like walking through a damp garden at dawn. Crushed mint leaves, wild basil, and lemon verbena rest on a light base of clean musk and green vetiver.',
        price: 4200,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/lune_bleue.jpg', '/images/trio.png']),
        stock: 45,
        isFeatured: 0,
        topNotes: 'Spearmint, Wild Basil, Lemon',
        heartNotes: 'Verbena, Green Tea, Jasmine',
        baseNotes: 'Vetiver, White Musk, Cedarwood',
        tags: 'Fresh, Green, Citrus, Unisex',
      },
      {
        id: 'prod-cuir-sauvage',
        name: 'Cuir Sauvage',
        slug: 'cuir-sauvage',
        tagline: 'Smoky leather, cardamom, and warm tobacco.',
        description: 'A bold, sophisticated leather fragrance. Warm cardamom and raspberry give way to a heart of rugged black leather and tobacco leaves, finished with earthy oakmoss and amber.',
        price: 5100,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/epice_noire.jpg', '/images/trio.png']),
        stock: 20,
        isFeatured: 0,
        topNotes: 'Cardamom, Raspberry, Saffron',
        heartNotes: 'Tuscan Leather, Jasmine, Thyme',
        baseNotes: 'Amber, Oakmoss, Patchouli, Oud',
        tags: 'Leather, Smoky, Woody, Unisex',
      },
      {
        id: 'prod-nuit-blanche',
        name: 'Nuit Blanche',
        slug: 'nuit-blanche',
        tagline: 'Black coffee, white florals, and sweet vanilla.',
        description: 'An addictive, nocturnal fragrance of contrasts. Energetic black coffee beans and sweet orange blossom collide in a creamy base of vanilla, patchouli, and white musk.',
        price: 4800,
        compareAtPrice: 5800,
        imageUrls: JSON.stringify(['/images/epice_noire.jpg', '/images/trio.png']),
        stock: 35,
        isFeatured: 0,
        topNotes: 'Pink Pepper, Pear, Orange Blossom',
        heartNotes: 'Coffee, Jasmine, Bitter Almond',
        baseNotes: 'Vanilla, Patchouli, Cedarwood, Cashmere Wood',
        tags: 'Gourmand, Floral, Coffee, Unisex',
      },
      {
        id: 'prod-fleur-doranger',
        name: 'Fleur d\'Oranger',
        slug: 'fleur-doranger',
        tagline: 'Neroli, sun-kissed orange blossom, and clean musk.',
        description: 'A bright, radiant floral that captures the warmth of a Mediterranean summer. Sparkling neroli and sweet orange blossom are anchored by a clean base of musk and white honey.',
        price: 4500,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/citrus_zest.jpg', '/images/trio.png']),
        stock: 40,
        isFeatured: 0,
        topNotes: 'Neroli, Bergamot, Petitgrain',
        heartNotes: 'Orange Blossom, Jasmine, Tuberose',
        baseNotes: 'Musk, White Honey, Cedarwood',
        tags: 'Floral, Citrus, Clean, Unisex',
      },
      {
        id: 'prod-discovery-trio',
        name: 'VN Aroma Discovery Trio',
        slug: 'discovery-trio',
        tagline: 'Three iconic signatures in one luxury gift set.',
        description: 'The ultimate olfactory journey. Experience our entire launch collection featuring Lune Bleue, Épice Noire, and Inhale in individual 50ml bottles, presented in a minimal black-and-cream display box.',
        price: 11900,
        compareAtPrice: 13900,
        imageUrls: JSON.stringify(['/images/trio.png']),
        stock: 30,
        isFeatured: 1,
        topNotes: 'Citrus, Spices, Florals',
        heartNotes: 'Sea Salt, Cardamom, Rose',
        baseNotes: 'Woods, Amber, Musk',
        tags: 'Set, Unisex, Bestseller, Gift',
      },
      // NEW ADDITIONS (To reach 35 products)
      {
        id: 'prod-ambre-gris',
        name: 'Ambre Gris',
        slug: 'ambre-gris',
        tagline: 'Rich ambergris, mineral sea salt, and dry wood.',
        description: 'A warm, salty-sweet skin scent that mimics the heat of sea-drenched skin in the sun. Marine ambergris meets powdery iris, resting on dry sandalwood.',
        price: 5200,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/lune_bleue.jpg']),
        stock: 25,
        isFeatured: 0,
        topNotes: 'Sea Salt, Ozone',
        heartNotes: 'White Iris, Dry Amber',
        baseNotes: 'Natural Ambergris, Sandalwood, Musk',
        tags: 'Fresh, Marine, Amber, Unisex',
      },
      {
        id: 'prod-velvet-oud',
        name: 'Velvet Oud',
        slug: 'velvet-oud',
        tagline: 'Deep black cherry, dark leather, and resinous oud.',
        description: 'A luxurious, velvety scent that layers juicy dark cherries over a heavy base of smoked oud and supple black suede.',
        price: 5800,
        compareAtPrice: 6800,
        imageUrls: JSON.stringify(['/images/epice_noire.jpg']),
        stock: 30,
        isFeatured: 0,
        topNotes: 'Black Cherry, Saffron',
        heartNotes: 'Oud Wood, Rose Absolute',
        baseNotes: 'Black Leather, Patchouli, Amber',
        tags: 'Oud, Leather, Spicy, Unisex',
      },
      {
        id: 'prod-soleil-dor',
        name: 'Soleil d\'Or',
        slug: 'soleil-dor',
        tagline: 'Warm solar citrus, jasmine petals, and sweet coconut.',
        description: 'Captures the heat of mid-afternoon sunshine. Radiant orange blossoms and soft coconut milk rest on a warm base of ambergris and benzoin.',
        price: 4600,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/citrus_zest.jpg']),
        stock: 40,
        isFeatured: 0,
        topNotes: 'Bergamot, Mandarin, Solar Accord',
        heartNotes: 'Jasmine, Coconut Milk, Orange Blossom',
        baseNotes: 'Ambergris, Vanilla, Cedar',
        tags: 'Citrus, Floral, Unisex',
      },
      {
        id: 'prod-santal-royal',
        name: 'Santal Royal',
        slug: 'santal-royal',
        tagline: 'Creamy Mysore sandalwood, dry cedar, and cardamom.',
        description: 'A creamy wood masterpiece that feels like smooth timber. Fresh spices lead into rich, milky sandalwood and amber resin.',
        price: 4900,
        compareAtPrice: 5900,
        imageUrls: JSON.stringify(['/images/silver_birch.jpg']),
        stock: 35,
        isFeatured: 0,
        topNotes: 'Cardamom, Black Pepper',
        heartNotes: 'Mysore Sandalwood, Papyrus',
        baseNotes: 'Cedarwood, Amber, Leather',
        tags: 'Woody, Spicy, Unisex',
      },
      {
        id: 'prod-vert-sauvage',
        name: 'Vert Sauvage',
        slug: 'vert-sauvage',
        tagline: 'Crushed pine needles, wet oakmoss, and green ivy.',
        description: 'An aromatic green blast that mimics a high-altitude coniferous forest. Resin-rich pine and green ivy rest on cedarwood and forest floor moss.',
        price: 4300,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/silver_birch.jpg']),
        stock: 50,
        isFeatured: 0,
        topNotes: 'Pine Needles, Galbanum',
        heartNotes: 'Ivy Leaf, Juniper Berry',
        baseNotes: 'Oakmoss, Cedarwood, Vetiver',
        tags: 'Green, Woody, Unisex',
      },
      {
        id: 'prod-rose-poivree',
        name: 'Rose Poivrée',
        slug: 'rose-poivree',
        tagline: 'Szechuan pepper, damask rose, and earthy vetiver.',
        description: 'A prickly, modern rose fragrance. Spicy Szechuan peppercorns and green aldehydes slice through a heart of wet rose petals and cedar.',
        price: 4950,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/rose_gold_oud_1.jpg']),
        stock: 35,
        isFeatured: 0,
        topNotes: 'Szechuan Pepper, Pink Grapefruit',
        heartNotes: 'Damask Rose, Peony, Iris',
        baseNotes: 'Vetiver, Cashmere Wood, Musk',
        tags: 'Floral, Spicy, Unisex',
      },
      {
        id: 'prod-fumee-noire',
        name: 'Fumée Noire',
        slug: 'fumee-noire',
        tagline: 'Roasted birch tar, dry tobacco leaf, and patchouli.',
        description: 'Rich, dark, and highly enigmatic. Smoked birch woods and aged tobacco leaves are sweetened slightly by rich honey and warm amber resins.',
        price: 5200,
        compareAtPrice: 6200,
        imageUrls: JSON.stringify(['/images/epice_noire.jpg']),
        stock: 25,
        isFeatured: 0,
        topNotes: 'Smoked Birch, Clove',
        heartNotes: 'Tobacco Leaf, Cedarwood',
        baseNotes: 'Earthy Patchouli, Vetiver, Amber',
        tags: 'Woody, Smoky, Unisex',
      },
      {
        id: 'prod-musc-pur',
        name: 'Musc Pur',
        slug: 'musc-pur',
        tagline: 'Clean white musk, cotton blossoms, and soft aldehydes.',
        description: 'A cocooning, minimalist scent of pure comfort. A soft breeze of powdery aldehydes and cotton blossoms, resting on rich, clean white musk.',
        price: 4400,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/inhale.jpg']),
        stock: 45,
        isFeatured: 0,
        topNotes: 'Aldehydes, White Lily',
        heartNotes: 'Cotton Blossom, Powdery Iris',
        baseNotes: 'White Musk, Cashmere Wood',
        tags: 'Clean, Powdery, Unisex',
      },
      {
        id: 'prod-jasmin-nuit',
        name: 'Jasmin Nuit',
        slug: 'jasmin-nuit',
        tagline: 'Night-blooming jasmine, dark vanilla, and incense.',
        description: 'A seductive floral that blooms in the shadows. Heavy indolic jasmine petals are wrapped in dark vanilla pods and sweet incense smoke.',
        price: 4700,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/inhale.jpg']),
        stock: 40,
        isFeatured: 0,
        topNotes: 'Black Pepper, Clove',
        heartNotes: 'Night-Blooming Jasmine, Ylang-Ylang',
        baseNotes: 'Vanilla, Incense, Sandalwood',
        tags: 'Floral, Warm, Unisex',
      },
      {
        id: 'prod-cacao-noir',
        name: 'Cacao Noir',
        slug: 'cacao-noir',
        tagline: 'Rich dark cacao, roasted coffee beans, and spice.',
        description: 'An addictive gourmand composition. Bitter dark chocolate and freshly roasted espresso beans are warmed by cinnamon and sweet tonka.',
        price: 4900,
        compareAtPrice: 5800,
        imageUrls: JSON.stringify(['/images/epice_noire.jpg']),
        stock: 30,
        isFeatured: 0,
        topNotes: 'Cardamom, Cinnamon',
        heartNotes: 'Dark Cacao, Coffee Absolute',
        baseNotes: 'Roasted Tonka Bean, Vanilla, Patchouli',
        tags: 'Gourmand, Warm, Spicy, Unisex',
      },
      {
        id: 'prod-figuier-sauvage',
        name: 'Figuier Sauvage',
        slug: 'figuier-sauvage',
        tagline: 'Crushed fig leaf, milky fig wood, and coconut.',
        description: 'A sun-drenched Mediterranean fig tree. Captures the bitterness of the green leaf, the creaminess of fig sap, and the warmth of the wood.',
        price: 4500,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/silver_birch.jpg']),
        stock: 40,
        isFeatured: 0,
        topNotes: 'Fig Leaf, Mandarin',
        heartNotes: 'Fig Sap, Violet, Jasmine',
        baseNotes: 'Fig Wood, Coconut, Cedarwood',
        tags: 'Fresh, Green, Woody, Unisex',
      },
      {
        id: 'prod-menthe-fraiche',
        name: 'Menthe Fraîche',
        slug: 'menthe-fraiche',
        tagline: 'Wild peppermint, organic green tea, and cedar.',
        description: 'A cooling, aromatic wake-up call. Icy wild peppermint and crushed green tea leaves are grounded by clean cedarwood and white musk.',
        price: 4100,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/lune_bleue.jpg']),
        stock: 55,
        isFeatured: 0,
        topNotes: 'Wild Peppermint, Spearmint',
        heartNotes: 'Green Tea, Jasmine, Rosemary',
        baseNotes: 'White Musk, Atlas Cedarwood',
        tags: 'Fresh, Green, Unisex',
      },
      {
        id: 'prod-orangerie',
        name: 'Orangerie',
        slug: 'orangerie',
        tagline: 'Sun-ripened mandarin, orange blossom, and benzoin.',
        description: 'A sparkling citrus fragrance that captures the warmth of orange groves. A zesty mandarin opening leads into sweet orange blossoms.',
        price: 4400,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/citrus_zest.jpg']),
        stock: 45,
        isFeatured: 0,
        topNotes: 'Mandarin Peel, Bergamot',
        heartNotes: 'Orange Blossom, Neroli',
        baseNotes: 'Benzoin, White Honey, Cedarwood',
        tags: 'Citrus, Floral, Unisex',
      },
      {
        id: 'prod-vanille-absolue',
        name: 'Vanille Absolue',
        slug: 'vanille-absolue',
        tagline: 'Dark bourbon vanilla, roasted tonka, and amber.',
        description: 'A highly sophisticated vanilla. Free from synthetic candy sweetness, it features deep, woody vanilla pods and dark, warm resins.',
        price: 5100,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/rose_gold_oud_1.jpg']),
        stock: 35,
        isFeatured: 0,
        topNotes: 'Almond, Heliotrope',
        heartNotes: 'Bourbon Vanilla, Caramel',
        baseNotes: 'Roasted Tonka Bean, Sandalwood, Amber',
        tags: 'Gourmand, Warm, Unisex',
      },
      {
        id: 'prod-tabac-or',
        name: 'Tabac Or',
        slug: 'tabac-or',
        tagline: 'Sweet blonde tobacco, raw honey, and warm spices.',
        description: 'A rich, golden composition. Sweet pipe tobacco leaves are drenched in raw honey and spiced with cinnamon, clove, and vanilla.',
        price: 5300,
        compareAtPrice: 6300,
        imageUrls: JSON.stringify(['/images/epice_noire.jpg']),
        stock: 30,
        isFeatured: 0,
        topNotes: 'Cinnamon, Ginger',
        heartNotes: 'Blonde Tobacco Leaf, Honey, Cocoa',
        baseNotes: 'Bourbon Vanilla, Tonka, Amber',
        tags: 'Spicy, Warm, Honey, Unisex',
      },
      {
        id: 'prod-bois-dargent',
        name: 'Bois d\'Argent',
        slug: 'bois-dargent',
        tagline: 'White iris absolute, meditative myrrh, and cedar.',
        description: 'An elegant, powdery skin scent. Powdery white iris is contrasted by the smoky, balsamic warmth of natural myrrh and dry cedar.',
        price: 5500,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/silver_birch.jpg']),
        stock: 25,
        isFeatured: 0,
        topNotes: 'Juniper Berry, Cypress',
        heartNotes: 'White Iris Absolute, Myrrh, Patchouli',
        baseNotes: 'Leather, Vanilla, Cedarwood, Amber',
        tags: 'Woody, Powdery, Unisex',
      },
      {
        id: 'prod-rouge-cardinal',
        name: 'Rouge Cardinal',
        slug: 'rouge-cardinal',
        tagline: 'Tart red cranberry, crimson rose, and frankincense.',
        description: 'A striking, deep crimson fragrance. Sharp, tart cranberries and rich red roses are shrouded in cold frankincense smoke.',
        price: 5100,
        compareAtPrice: 6200,
        imageUrls: JSON.stringify(['/images/rose_gold_oud_1.jpg']),
        stock: 30,
        isFeatured: 0,
        topNotes: 'Cranberry, Saffron, Pink Pepper',
        heartNotes: 'Crimson Rose Absolute, Iris, Clove',
        baseNotes: 'Frankincense, Patchouli, Benzoin',
        tags: 'Floral, Incense, Fruity, Unisex',
      },
      {
        id: 'prod-vetiver-dore',
        name: 'Vetiver Doré',
        slug: 'vetiver-dore',
        tagline: 'Smoky Haitian vetiver, nutmeg, and warm gold amber.',
        description: 'A golden, dry vetiver. Earthy, grassy roots are roasted and blended with warm nutmeg, cedarwood, and rich amber resins.',
        price: 4800,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/silver_birch.jpg']),
        stock: 35,
        isFeatured: 0,
        topNotes: 'Bergamot, Nutmeg',
        heartNotes: 'Haitian Vetiver, Cedarwood',
        baseNotes: 'Warm Amber, Oakmoss, Musk',
        tags: 'Woody, Earthy, Warm, Unisex',
      },
      {
        id: 'prod-citron-presse',
        name: 'Citron Pressé',
        slug: 'citron-presse',
        tagline: 'Freshly squeezed lemon peel, wild mint, and cane sugar.',
        description: 'A refreshing, sparkling lemonade. Zesty lemon peel and refreshing peppermint leaves rest on a base of sweet cane sugar and white musk.',
        price: 3900,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/citrus_zest.jpg']),
        stock: 50,
        isFeatured: 0,
        topNotes: 'Lemon Peel, Lime, Verbena',
        heartNotes: 'Peppermint, Jasmine, Lemongrass',
        baseNotes: 'Cane Sugar, White Musk',
        tags: 'Citrus, Fresh, Unisex',
      },
      {
        id: 'prod-patchouli-noir',
        name: 'Patchouli Noir',
        slug: 'patchouli-noir',
        tagline: 'Earthy dark patchouli, cocoa dust, and white musk.',
        description: 'A dark, gothic interpretation of patchouli. Earthy patchouli leaves are dusted with bitter cocoa powder and wrapped in clean white musk.',
        price: 5000,
        compareAtPrice: 6000,
        imageUrls: JSON.stringify(['/images/epice_noire.jpg']),
        stock: 35,
        isFeatured: 0,
        topNotes: 'Black Pepper, Coriander',
        heartNotes: 'Dark Patchouli, Cacao Powder, Cedar',
        baseNotes: 'White Musk, Ambergris, Oakmoss',
        tags: 'Woody, Earthy, Unisex',
      },
      {
        id: 'prod-cuir-violette',
        name: 'Cuir Violette',
        slug: 'cuir-violette',
        tagline: 'Powdery violet blossom, dark suede, and dry wood.',
        description: 'An elegant floral-leather contrast. Sweet, powdery violet flower sits against a rugged backdrop of dark, smoky suede leather.',
        price: 5200,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/inhale.jpg']),
        stock: 30,
        isFeatured: 0,
        topNotes: 'Violet Flower, Saffron',
        heartNotes: 'Suede, Orris Root, Jasmine',
        baseNotes: 'Atlas Cedarwood, Tobacco, Amber',
        tags: 'Floral, Leather, Unisex',
      },
      {
        id: 'prod-brume-celeste',
        name: 'Brume Céleste',
        slug: 'brume-celeste',
        tagline: 'Luminous aldehydes, mineral rain, and white musk.',
        description: 'A clean, atmospheric fragrance that mimics the smell of clean air after a rainstorm. Sparkling aldehydes lead to wet iris, resting on white musk.',
        price: 4600,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/lune_bleue.jpg']),
        stock: 40,
        isFeatured: 0,
        topNotes: 'Luminous Aldehydes, Ozone, Rain Accord',
        heartNotes: 'White Iris, Lily of the Valley',
        baseNotes: 'Clean White Musk, Sandalwood',
        tags: 'Clean, Fresh, Unisex',
      }
    ];

    // Seed Products and Variants
    for (const prod of perfumesData) {
      await db.insert(products).values({
        id: prod.id,
        name: prod.name,
        slug: prod.slug,
        tagline: prod.tagline,
        description: prod.description,
        price: prod.price,
        compareAtPrice: prod.compareAtPrice,
        imageUrls: prod.imageUrls,
        stock: prod.stock,
        isFeatured: prod.isFeatured,
        topNotes: prod.topNotes,
        heartNotes: prod.heartNotes,
        baseNotes: prod.baseNotes,
        tags: prod.tags,
        createdAt: Math.floor(Date.now() / 1000),
      });

      // Seeding variants for each individual perfume (except the trio bundle itself which is fixed at 3x50ml)
      if (prod.id !== 'prod-discovery-trio') {
        // 30ml variant
        await db.insert(variants).values({
          id: `var-${prod.slug}-30`,
          productId: prod.id,
          size: '30ml',
          price: Math.floor(prod.price * 0.75), // 25% discount for smaller size
          stock: Math.floor(prod.stock * 0.6),
        });

        // 50ml variant (Default size matching product base price)
        await db.insert(variants).values({
          id: `var-${prod.slug}-50`,
          productId: prod.id,
          size: '50ml',
          price: prod.price,
          stock: prod.stock,
        });

        // 100ml variant
        await db.insert(variants).values({
          id: `var-${prod.slug}-100`,
          productId: prod.id,
          size: '100ml',
          price: Math.floor(prod.price * 1.65), // cheaper per ml
          stock: Math.floor(prod.stock * 0.4),
        });
      } else {
        // Trio Bundle variant
        await db.insert(variants).values({
          id: 'var-discovery-trio-3x50ml',
          productId: prod.id,
          size: '3 x 50ml',
          price: prod.price,
          stock: prod.stock,
        });
      }
    }

    return NextResponse.json({ success: true, message: 'Database successfully re-seeded with 35 luxury perfumes, variants, and admin user.' });
  } catch (e: any) {
    console.error('Seeding failed:', e);
    return NextResponse.json({ success: false, error: e.message }, { status: 500 });
  }
}
