import { NextResponse } from 'next/server';
import { getDb } from '@/db';
import { users, products, variants } from '@/db/schema';
import { eq } from 'drizzle-orm';

export const runtime = 'edge';
export const dynamic = 'force-dynamic';

// Web Crypto PBKDF2 Password Hashing Helper
async function hashPassword(password: string): Promise<string> {
  const encoder = new TextEncoder();
  const passwordBuffer = encoder.encode(password);
  const salt = crypto.getRandomValues(new Uint8Array(16));

  const baseKey = await crypto.subtle.importKey(
    'raw',
    passwordBuffer,
    { name: 'PBKDF2' },
    false,
    ['deriveBits', 'deriveKey']
  );

  const derivedKeyBits = await crypto.subtle.deriveBits(
    {
      name: 'PBKDF2',
      salt: salt,
      iterations: 100000,
      hash: 'SHA-256'
    },
    baseKey,
    256
  );

  const saltHex = Array.from(salt).map(b => b.toString(16).padStart(2, '0')).join('');
  const keyHex = Array.from(new Uint8Array(derivedKeyBits)).map(b => b.toString(16).padStart(2, '0')).join('');

  return `${saltHex}:${keyHex}`;
}

export async function GET() {
  try {
    const db = getDb();

    // 1. Create tables if they do not exist
    const createTableQueries = [
      `CREATE TABLE IF NOT EXISTS users (
        id TEXT PRIMARY KEY,
        email TEXT UNIQUE NOT NULL,
        password_hash TEXT NOT NULL,
        name TEXT NOT NULL,
        role TEXT NOT NULL DEFAULT 'user',
        created_at INTEGER NOT NULL
      );`,
      `CREATE TABLE IF NOT EXISTS products (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        slug TEXT UNIQUE NOT NULL,
        tagline TEXT NOT NULL,
        description TEXT NOT NULL,
        price INTEGER NOT NULL,
        compare_at_price INTEGER,
        image_urls TEXT NOT NULL,
        stock INTEGER NOT NULL DEFAULT 0,
        is_featured INTEGER NOT NULL DEFAULT 0,
        top_notes TEXT NOT NULL,
        heart_notes TEXT NOT NULL,
        base_notes TEXT NOT NULL,
        tags TEXT NOT NULL,
        created_at INTEGER NOT NULL
      );`,
      `CREATE TABLE IF NOT EXISTS variants (
        id TEXT PRIMARY KEY,
        product_id TEXT NOT NULL,
        size TEXT NOT NULL,
        price INTEGER NOT NULL,
        stock INTEGER NOT NULL DEFAULT 0,
        FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE
      );`,
      `CREATE TABLE IF NOT EXISTS orders (
        id TEXT PRIMARY KEY,
        user_id TEXT,
        order_number TEXT UNIQUE NOT NULL,
        total_amount INTEGER NOT NULL,
        shipping_address TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'Processing',
        payment_status TEXT NOT NULL DEFAULT 'Pending',
        razorpay_order_id TEXT,
        razorpay_payment_id TEXT,
        created_at INTEGER NOT NULL,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
      );`,
      `CREATE TABLE IF NOT EXISTS order_items (
        id TEXT PRIMARY KEY,
        order_id TEXT NOT NULL,
        product_id TEXT NOT NULL,
        variant_id TEXT,
        quantity INTEGER NOT NULL,
        price_at_purchase INTEGER NOT NULL,
        size TEXT NOT NULL,
        FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,
        FOREIGN KEY(product_id) REFERENCES products(id)
      );`,
      `CREATE TABLE IF NOT EXISTS cart_items (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        product_id TEXT NOT NULL,
        variant_id TEXT,
        quantity INTEGER NOT NULL DEFAULT 1,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
        FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE
      );`
    ];

    for (const query of createTableQueries) {
      await db.run(query);
    }

    // 2. Clear existing seed data to ensure fresh seed
    await db.delete(variants);
    await db.delete(products);

    // 3. Create Admin User if not exists
    const adminEmail = 'admin@vnaroma.com';
    const existingAdmin = await db.select().from(users).where(eq(users.email, adminEmail)).get();
    
    if (!existingAdmin) {
      const hashedAdminPassword = await hashPassword('admin123');
      await db.insert(users).values({
        id: crypto.randomUUID(),
        email: adminEmail,
        passwordHash: hashedAdminPassword,
        name: 'VN Aroma Admin',
        role: 'admin',
        createdAt: Math.floor(Date.now() / 1000),
      });
    }

    // 4. 35 Luxury Perfumes Dataset
    const perfumesData = [
      {
        id: 'prod-lune-bleue',
        name: 'Lune Bleue',
        slug: 'lune-bleue',
        tagline: 'Citrus, sea salt, and whispers of moonlight.',
        description: 'A luminous and fresh fragrance inspired by cool ocean breezes under a full moon. Bright grapefruit and sea salt open into a heart of mineral sage, grounded by dark cedarwood and soft musk. Clean, marine, and elegant.',
        price: 4500,
        compareAtPrice: 5500,
        imageUrls: JSON.stringify(['/images/lune_bleue.jpg', '/images/trio.png']),
        stock: 50,
        isFeatured: 1,
        topNotes: 'Bergamot, Grapefruit, Sea Accord',
        heartNotes: 'Sea Salt, Sage, Rosemary',
        baseNotes: 'Cedarwood, Ambergris, Musk',
        tags: 'Fresh, Marine, Unisex, Bestseller',
      },
      {
        id: 'prod-epice-noire',
        name: 'Épice Noire',
        slug: 'epice-noire',
        tagline: 'Warm amber, black pepper, and sacred woods.',
        description: 'A rich, seductive, and complex fragrance that captures the warmth of oriental spices. Bold black pepper and aromatic cardamom fuse with cinnamon and cloves, resting on a base of creamy sandalwood and rich amber.',
        price: 4800,
        compareAtPrice: 5800,
        imageUrls: JSON.stringify(['/images/epice_noire.jpg', '/images/trio.png']),
        stock: 40,
        isFeatured: 1,
        topNotes: 'Black Pepper, Cardamom, Bergamot',
        heartNotes: 'Cinnamon, Clove, Nutmeg',
        baseNotes: 'Sandalwood, Patchouli, Amber, Vanilla',
        tags: 'Spicy, Amber, Woody, Unisex, Bestseller',
      },
      {
        id: 'prod-inhale',
        name: 'Inhale',
        slug: 'inhale',
        tagline: 'Soft rose, lychee, and fresh linen.',
        description: 'A clean, soft, and powdery floral fragrance that evokes the purity of morning light and fresh linen. Crisp pear and sweet lychee lead to a heart of blooming rose and peony, ending in a warm cashmere wood embrace.',
        price: 4600,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/inhale.jpg', '/images/trio.png']),
        stock: 60,
        isFeatured: 1,
        topNotes: 'Pear, Lychee, Aldehydes',
        heartNotes: 'Damask Rose, Peony, Freesia',
        baseNotes: 'White Musk, Sandalwood, Cashmere Wood',
        tags: 'Floral, Clean, Powdery, Unisex, New Arrival',
      },
      {
        id: 'prod-citrus-zest',
        name: 'Citrus Zest',
        slug: 'citrus-zest',
        tagline: 'Bright mandarin peel, Sicilian lemon, and green verbena.',
        description: 'An energizing, sun-kissed citrus blast that captures the crisp air of Amalfi. Lush lemon verbena and fresh bergamot open into orange blossom, resting on white honey and clean cedar wood.',
        price: 4200,
        compareAtPrice: 5200,
        imageUrls: JSON.stringify(['/images/citrus_zest.jpg', '/images/trio.png']),
        stock: 45,
        isFeatured: 1,
        topNotes: 'Amalfi Lemon, Bergamot, Grapefruit',
        heartNotes: 'Orange Blossom, Lime Leaf, Mint',
        baseNotes: 'White Honey, Cedarwood, Musk',
        tags: 'Citrus, Fresh, Unisex, Bestseller',
      },
      {
        id: 'prod-silver-birch',
        name: 'Silver Birch',
        slug: 'silver-birch',
        tagline: 'Earthy wood, birch bark, and crisp winter air.',
        description: 'A clean, mineral, wood-centric fragrance that feels like walking through a damp birch forest in early winter. Fresh silver leaf pine opens into birch bark, grounded by rich vetiver and patchouli.',
        price: 4700,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/silver_birch.jpg', '/images/trio.png']),
        stock: 35,
        isFeatured: 1,
        topNotes: 'Pine Needles, White Iris',
        heartNotes: 'Birch Wood, Cedarwood, Juniper',
        baseNotes: 'Earthy Vetiver, Oakmoss, Patchouli',
        tags: 'Woody, Fresh, Unisex, New Arrival',
      },
      {
        id: 'prod-rose-gold-oud',
        name: 'Rose Gold Oud',
        slug: 'rose-gold-oud',
        tagline: 'Turkish rose absolute, saffron, and golden incense.',
        description: 'A dramatic, opulent, oriental floral masterpiece. Precious Damask Rose is wrapped in warm saffron and gold resin incense, resting on a base of rich Cambodian oud and bourbon vanilla.',
        price: 5400,
        compareAtPrice: 6500,
        imageUrls: JSON.stringify(['/images/rose_gold_oud_1.jpg', '/images/rose_gold_oud_2.jpg', '/images/rose_gold_oud_3.jpg']),
        stock: 30,
        isFeatured: 1,
        topNotes: 'Saffron, Pink Pepper, Red Berries',
        heartNotes: 'Damask Rose, Jasmine, Praline',
        baseNotes: 'Oud Wood, Frankincense, Vanilla, Amber',
        tags: 'Floral, Oud, Spicy, Unisex, Bestseller',
      },
      {
        id: 'prod-cedarwood-peak',
        name: 'Cedarwood Peak',
        slug: 'cedarwood-peak',
        tagline: 'Atlas cedar wood, crisp mountain air, and dry pine needles.',
        description: 'An elegant, crisp woody fragrance inspired by high summits. Clean alpine air and dry pine needles settle into a heart of rich cedarwood, finished with oakmoss and patchouli.',
        price: 4900,
        compareAtPrice: 6200,
        imageUrls: JSON.stringify(['/images/cedarwood_peak.jpg']),
        stock: 30,
        isFeatured: 0,
        topNotes: 'Alpine Accord, Pine Needles, Bergamot',
        heartNotes: 'Atlas Cedarwood, Cypress, Juniper',
        baseNotes: 'Oakmoss, Patchouli, Dry Wood',
        tags: 'Woody, Fresh, Unisex',
      },
      {
        id: 'prod-velvet-orchid',
        name: 'Velvet Orchid',
        slug: 'velvet-orchid',
        tagline: 'Deep black orchid, velvety vanilla, and dark amber.',
        description: 'An opulent, sensual floral masterpiece. Crimson orchids and white jasmine are cradled on soft velvet pillows, wrapped in the warmth of sweet Madagascar vanilla, dark honey, and rich amber.',
        price: 5200,
        compareAtPrice: 6500,
        imageUrls: JSON.stringify(['/images/velvet_orchid.jpg']),
        stock: 25,
        isFeatured: 0,
        topNotes: 'Black Cherry, Pink Pepper, Rum Accord',
        heartNotes: 'Velvet Orchid, White Jasmine, Gardenia',
        baseNotes: 'Madagascar Vanilla, Amber, Sandalwood',
        tags: 'Floral, Amber, Sweet, Unisex',
      },
      {
        id: 'prod-oceanic-breeze',
        name: 'Oceanic Breeze',
        slug: 'oceanic-breeze',
        tagline: 'Crashing ocean waves, wet rocks, and refreshing sea spray.',
        description: 'An invigorating marine creation inspired by stormy coastlines. Crisp ozone and salt spray lead to cold water lily and kelp, resting on wet pebbles and clean moss.',
        price: 4500,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/oceanic_breeze.jpg']),
        stock: 45,
        isFeatured: 0,
        topNotes: 'Sea Salt, Ozone, Bergamot',
        heartNotes: 'Water Lily, Kelp, Rosemary',
        baseNotes: 'Wet Stones, Oakmoss, Ambergris',
        tags: 'Fresh, Marine, Unisex',
      },
      {
        id: 'prod-cuir-sauvage',
        name: 'Cuir Sauvage',
        slug: 'cuir-sauvage',
        tagline: 'Smoky leather, cardamom, and warm tobacco.',
        description: 'A bold, sophisticated leather fragrance. Warm cardamom and raspberry give way to a heart of rugged black leather and tobacco leaves, finished with earthy oakmoss and amber.',
        price: 5100,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/epice_noire.jpg', '/images/trio.png']),
        stock: 20,
        isFeatured: 0,
        topNotes: 'Cardamom, Raspberry, Saffron',
        heartNotes: 'Tuscan Leather, Jasmine, Thyme',
        baseNotes: 'Amber, Oakmoss, Patchouli, Oud',
        tags: 'Leather, Smoky, Woody, Unisex',
      },
      {
        id: 'prod-nuit-blanche',
        name: 'Nuit Blanche',
        slug: 'nuit-blanche',
        tagline: 'Black coffee, white florals, and sweet vanilla.',
        description: 'An addictive, nocturnal fragrance of contrasts. Energetic black coffee beans and sweet orange blossom collide in a creamy base of vanilla, patchouli, and white musk.',
        price: 4800,
        compareAtPrice: 5800,
        imageUrls: JSON.stringify(['/images/epice_noire.jpg', '/images/trio.png']),
        stock: 35,
        isFeatured: 0,
        topNotes: 'Pink Pepper, Pear, Orange Blossom',
        heartNotes: 'Coffee, Jasmine, Bitter Almond',
        baseNotes: 'Vanilla, Patchouli, Cedarwood, Cashmere Wood',
        tags: 'Gourmand, Floral, Coffee, Unisex',
      },
      {
        id: 'prod-pure-jasmine',
        name: 'Pure Jasmine',
        slug: 'pure-jasmine',
        tagline: 'Luminous jasmine blossoms, white marble, and morning greenhouse warmth.',
        description: 'A bright, clean, single-note floral tribute. Luminous white jasmine blossoms are set on polished marble blocks inside a warm greenhouse, blending with green leaves and a hint of musk.',
        price: 4500,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/pure_jasmine.jpg']),
        stock: 40,
        isFeatured: 0,
        topNotes: 'Jasmine Sambac, Bergamot, Green Leaves',
        heartNotes: 'Star Jasmine, Orange Blossom, Lily',
        baseNotes: 'Clean White Musk, Soft Sandalwood',
        tags: 'Floral, Clean, Unisex',
      },
      {
        id: 'prod-discovery-trio',
        name: 'VN Aroma Discovery Trio',
        slug: 'discovery-trio',
        tagline: 'Three iconic signatures in one luxury gift set.',
        description: 'The ultimate olfactory journey. Experience our entire launch collection featuring Lune Bleue, Épice Noire, and Inhale in individual 50ml bottles, presented in a minimal black-and-cream display box.',
        price: 11900,
        compareAtPrice: 13900,
        imageUrls: JSON.stringify(['/images/trio.png']),
        stock: 30,
        isFeatured: 1,
        topNotes: 'Citrus, Spices, Florals',
        heartNotes: 'Sea Salt, Cardamom, Rose',
        baseNotes: 'Woods, Amber, Musk',
        tags: 'Set, Unisex, Bestseller, Gift',
      },
      // NEW ADDITIONS (To reach 35 products)
      {
        id: 'prod-sweet-lychee',
        name: 'Sweet Lychee',
        slug: 'sweet-lychee',
        tagline: 'Freshly peeled sweet lychee, pink liquid, and clean linen.',
        description: 'A delightful, sparkling fruity-floral scent. Freshly peeled sweet lychees and red berries rest on a white tablecloth, melting into soft pink rose petals and clean white linen.',
        price: 5200,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/sweet_lychee.jpg']),
        stock: 25,
        isFeatured: 0,
        topNotes: 'Sweet Lychee, Red Currant, Pear',
        heartNotes: 'Pink Rose, Freesia, Lily of the Valley',
        baseNotes: 'Clean Linen Accord, White Musk, Sandalwood',
        tags: 'Floral, Fresh, Unisex',
      },
      {
        id: 'prod-velvet-oud',
        name: 'Velvet Oud',
        slug: 'velvet-oud',
        tagline: 'Deep black cherry, dark leather, and resinous oud.',
        description: 'A luxurious, velvety scent that layers juicy dark cherries over a heavy base of smoked oud and supple black suede.',
        price: 5800,
        compareAtPrice: 6800,
        imageUrls: JSON.stringify(['/images/epice_noire.jpg']),
        stock: 30,
        isFeatured: 0,
        topNotes: 'Black Cherry, Saffron',
        heartNotes: 'Oud Wood, Rose Absolute',
        baseNotes: 'Black Leather, Patchouli, Amber',
        tags: 'Oud, Leather, Spicy, Unisex',
      },
      {
        id: 'prod-hibiscus-sky',
        name: 'Hibiscus Sky',
        slug: 'hibiscus-sky',
        tagline: 'Frosted hibiscus flower, warm ocean sunset, and soft amber.',
        description: 'A glowing, tropical-floral fragrance. Sun-drenched pink hibiscus petals are set on a warm marble stand, reflecting the golden hues of an ocean sunset with soft vanilla amber.',
        price: 4600,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/hibiscus_sky.jpg']),
        stock: 40,
        isFeatured: 0,
        topNotes: 'Hibiscus, Mandarin, Red Berries',
        heartNotes: 'Plumeria, Coconut Water, White Rose',
        baseNotes: 'Solar Amber, Vanilla Pod, Soft Musk',
        tags: 'Floral, Amber, Unisex',
      },
      {
        id: 'prod-sandalwood-sun',
        name: 'Sandalwood Sun',
        slug: 'sandalwood-sun',
        tagline: 'Golden desert sandalwood, sun-warmed amber, and cardamom.',
        description: 'A glowing, solar amber-woody fragrance. Golden Mysore sandalwood is warmed by spicy cardamom, soft desert sand Accord, and sun-kissed amber resins.',
        price: 4900,
        compareAtPrice: 5900,
        imageUrls: JSON.stringify(['/images/sandalwood_sun.jpg']),
        stock: 35,
        isFeatured: 0,
        topNotes: 'Cardamom, Saffron, Bergamot',
        heartNotes: 'Mysore Sandalwood, Cashmere Wood, Warm Sand',
        baseNotes: 'Golden Amber, Cedarwood, Vanilla',
        tags: 'Woody, Amber, Spicy, Unisex',
      },
      {
        id: 'prod-white-tea-thyme',
        name: 'White Tea & Thyme',
        slug: 'white-tea-thyme',
        tagline: 'Delicate white tea buds, fresh thyme sprigs, and botanical clarity.',
        description: 'A clean, crisp, and meditative herbal-tea fragrance. Fresh white tea leaves and green thyme sprigs rest on a clean ceramic platter, opening into a calming base of musk and cedar.',
        price: 4300,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/white_tea_thyme.jpg']),
        stock: 50,
        isFeatured: 0,
        topNotes: 'White Tea, Bergamot, Coriander',
        heartNotes: 'Thyme, Sage, White Rose',
        baseNotes: 'White Musk, Cedarwood, Amber',
        tags: 'Fresh, Green, Tea, Unisex',
      },
      {
        id: 'prod-peony-silk',
        name: 'Peony Silk',
        slug: 'peony-silk',
        tagline: 'Soft peony petals, smooth pink satin, and white honey.',
        description: 'A delicate, powdery-fresh skin fragrance. Dewy pink peonies and fresh white rosebuds are cradled in smooth, shimmering pink satin sheets, sweetened by a drop of organic white honey.',
        price: 4950,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/peony_silk.jpg']),
        stock: 35,
        isFeatured: 0,
        topNotes: 'Pink Peony, Morning Dew, Mandora',
        heartNotes: 'White Rose, Powdery Iris, Silk Accord',
        baseNotes: 'White Honey, Cashmere Wood, Soft Musk',
        tags: 'Floral, Powdery, Unisex',
      },
      {
        id: 'prod-alpine-air',
        name: 'Alpine Air',
        slug: 'alpine-air',
        tagline: 'Crisp mountain wind, glacial stream water, and white snow.',
        description: 'An invigorating, ultra-clean scent that captures high summits. Icy mineral air and frozen glacier water notes rest on a base of clean pine needle absolute and cold woods.',
        price: 5200,
        compareAtPrice: 6200,
        imageUrls: JSON.stringify(['/images/alpine_air.jpg']),
        stock: 25,
        isFeatured: 0,
        topNotes: 'Glacial Accord, Crisp Oxygen, Mint Leaf',
        heartNotes: 'Snow Blossom, Juniper, Pine needles',
        baseNotes: 'Frozen Cedar, Oakmoss, Clean Musk',
        tags: 'Fresh, Marine, Unisex',
      },
      {
        id: 'prod-lavender-fields',
        name: 'Lavender Fields',
        slug: 'lavender-fields',
        tagline: 'Sunlit wild lavender, sweet powdery iris, and warm cashmere.',
        description: 'A clean, calming, and powdery floral dream. Freshly harvested wild French lavender and morning blossom open into powdery iris and soft violet, landing on comforting cashmere woods and white musk.',
        price: 4400,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/lavender_fields.jpg']),
        stock: 45,
        isFeatured: 0,
        topNotes: 'Wild Lavender, Bergamot, Sage',
        heartNotes: 'Iris, Violet, White Honey',
        baseNotes: 'Cashmere Wood, Powdery Musk, Amber',
        tags: 'Floral, Clean, Powdery, Unisex',
      },
      {
        id: 'prod-midnight-jasmine',
        name: 'Midnight Jasmine',
        slug: 'midnight-jasmine',
        tagline: 'Night-blooming jasmine petals, soft moonlight, and dark vanilla.',
        description: 'A seductive, nocturnal floral masterpiece. Intoxicating night-blooming jasmine blossoms are cradled on cold stone ledges under the moon, wrapped in balsamic incense smoke and dark vanilla bean.',
        price: 4700,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/midnight_jasmine.jpg']),
        stock: 40,
        isFeatured: 0,
        topNotes: 'Black Pepper, Clove, Morning Dew',
        heartNotes: 'Night-Blooming Jasmine, White Lily, Ylang-Ylang',
        baseNotes: 'Balsamic Incense, Madagascar Vanilla, Sandalwood',
        tags: 'Floral, Warm, Incense, Unisex',
      },
      {
        id: 'prod-ginger-lily',
        name: 'Ginger Lily',
        slug: 'ginger-lily',
        tagline: 'Fresh ginger root, orange flame lily, and botanical warmth.',
        description: 'A vibrant, spicy-floral masterwork. Zesty, freshly cut ginger root and orange flame lily petals create an uplifting opening, resting on a base of soft amber and warm cedar.',
        price: 4900,
        compareAtPrice: 5800,
        imageUrls: JSON.stringify(['/images/ginger_lily.jpg']),
        stock: 30,
        isFeatured: 0,
        topNotes: 'Fresh Ginger, Bergamot, Pink Pepper',
        heartNotes: 'Ginger Lily, Jasmine, Hibiscus',
        baseNotes: 'Cedarwood, Warm Amber, Musk',
        tags: 'Floral, Spicy, Fresh, Unisex',
      },
      {
        id: 'prod-bamboo-mist',
        name: 'Bamboo Mist',
        slug: 'bamboo-mist',
        tagline: 'Dewy green bamboo, white marble pedestal, and soft forest light.',
        description: 'A calming, architectural green fragrance. Freshly cut stems of green bamboo rest on white marble steps, reflecting light through a sun-dappled morning forest canopy.',
        price: 4500,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/bamboo_mist.jpg']),
        stock: 40,
        isFeatured: 0,
        topNotes: 'Green Bamboo, Cucumber Water, Dewy Grass',
        heartNotes: 'Green Tea, Lotus Petals, White Lily',
        baseNotes: 'Soft Woods, Clean Musk, Vetiver',
        tags: 'Fresh, Green, Unisex',
      },
      {
        id: 'prod-sapphire-mint',
        name: 'Sapphire Mint',
        slug: 'sapphire-mint',
        tagline: 'Icy wild peppermint, crushed green tea, and frozen crystal woods.',
        description: 'An ultra-refreshing, botanical blast. Frosty wild peppermint leaves and organic green tea are set on large crystal ice blocks, resting on a base of clean pine and winter wood notes.',
        price: 4100,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/sapphire_mint.jpg']),
        stock: 55,
        isFeatured: 0,
        topNotes: 'Wild Peppermint, Spearmint, Icy Ozone',
        heartNotes: 'Green Tea, Eucalyptus, Sage',
        baseNotes: 'Cedarwood, Frost Accord, White Musk',
        tags: 'Fresh, Green, Unisex',
      },
      {
        id: 'prod-bergamot-breeze',
        name: 'Bergamot Breeze',
        slug: 'bergamot-breeze',
        tagline: 'Zesty bergamot peel, fresh lime leaves, and morning greenhouse breeze.',
        description: 'A clean, uplifting citrus fragrance. Zesty fresh bergamot and lime peels sit on a white pedestal, surrounded by tiny white citrus blossoms and a gentle morning greenhouse breeze.',
        price: 4400,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/bergamot_breeze.jpg']),
        stock: 45,
        isFeatured: 0,
        topNotes: 'Bergamot Peel, Lime Leaf, Grapefruit',
        heartNotes: 'Neroli, Green Tea, Jasmine',
        baseNotes: 'White Musk, Cedarwood, Vetiver',
        tags: 'Citrus, Fresh, Clean, Unisex',
      },
      {
        id: 'prod-clean-cotton',
        name: 'Clean Cotton',
        slug: 'clean-cotton',
        tagline: 'Freshly folded white sheets, clean laundry, and warm morning sun.',
        description: 'A soothing, pure home-and-skin scent. Freshly laundered white towels sit in a stack by a sunny window, releasing a powdery breeze of clean white musk and aldehyde notes.',
        price: 5100,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/clean_cotton.jpg']),
        stock: 35,
        isFeatured: 0,
        topNotes: 'Powdery Aldehydes, White Lily, Clean Air',
        heartNotes: 'Cotton Blossom, Violet Leaf, White Rose',
        baseNotes: 'Pure White Musk, Sandalwood, Soft Amber',
        tags: 'Clean, Powdery, Unisex',
      },
      {
        id: 'prod-honey-blossom',
        name: 'Honey Blossom',
        slug: 'honey-blossom',
        tagline: 'Dripping raw honeycomb, orange blossom, and warm table wood.',
        description: 'An addictive, golden nectar fragrance. Freshly cut blocks of raw honeycomb sit on a sun-dappled table, surrounded by fragrant white orange blossoms and a hint of warm honey absolute.',
        price: 5300,
        compareAtPrice: 6300,
        imageUrls: JSON.stringify(['/images/honey_blossom.jpg']),
        stock: 30,
        isFeatured: 0,
        topNotes: 'Orange Blossom, Lemon Nectar',
        heartNotes: 'Raw Honeycomb, White Rose, Beeswax',
        baseNotes: 'Golden Amber, Vanilla Pod, Cedarwood',
        tags: 'Floral, Amber, Sweet, Unisex',
      },
      {
        id: 'prod-white-freesia',
        name: 'White Freesia',
        slug: 'white-freesia',
        tagline: 'Delicate freesia petals, white marble, and powdery breeze.',
        description: 'A clean, soft, and powdery floral fragrance. Elegant white freesia petals are set on a white marble pedestal, releasing a powdery breeze that blends into light woods and white musk.',
        price: 5500,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/white_freesia.jpg']),
        stock: 25,
        isFeatured: 0,
        topNotes: 'White Freesia, Pear Blossom, Aldehydes',
        heartNotes: 'Lily of the Valley, Jasmine, Peony',
        baseNotes: 'White Musk, Sandalwood, Cashmere Wood',
        tags: 'Floral, Fresh, Powdery, Unisex',
      },
      {
        id: 'prod-rouge-cardinal',
        name: 'Rouge Cardinal',
        slug: 'rouge-cardinal',
        tagline: 'Tart red cranberry, crimson rose, and frankincense.',
        description: 'A striking, deep crimson fragrance. Sharp, tart cranberries and rich red roses are shrouded in cold frankincense smoke.',
        price: 5100,
        compareAtPrice: 6200,
        imageUrls: JSON.stringify(['/images/rose_gold_oud_1.jpg']),
        stock: 30,
        isFeatured: 0,
        topNotes: 'Cranberry, Saffron, Pink Pepper',
        heartNotes: 'Crimson Rose Absolute, Iris, Clove',
        baseNotes: 'Frankincense, Patchouli, Benzoin',
        tags: 'Floral, Incense, Fruity, Unisex',
      },
      {
        id: 'prod-emerald-vetiver',
        name: 'Emerald Vetiver',
        slug: 'emerald-vetiver',
        tagline: 'Earthy smoked vetiver, wild forest ferns, and moss.',
        description: 'A damp, mysterious forest fragrance. Smoked Haitian vetiver is wrapped in rich, green ferns and wet moss, rising from a misty, resinous woodland base.',
        price: 4800,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/emerald_vetiver.jpg']),
        stock: 35,
        isFeatured: 0,
        topNotes: 'Forest Mist Accord, Grapefruit, Galbanum',
        heartNotes: 'Green Fern, Juniper, Coriander',
        baseNotes: 'Smoked Vetiver, Oakmoss, Patchouli',
        tags: 'Woody, Earthy, Unisex',
      },
      {
        id: 'prod-citron-presse',
        name: 'Citron Pressé',
        slug: 'citron-presse',
        tagline: 'Freshly squeezed lemon peel, wild mint, and cane sugar.',
        description: 'A refreshing, sparkling lemonade. Zesty lemon peel and refreshing peppermint leaves rest on a base of sweet cane sugar and white musk.',
        price: 3900,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/citrus_zest.jpg']),
        stock: 50,
        isFeatured: 0,
        topNotes: 'Lemon Peel, Lime, Verbena',
        heartNotes: 'Peppermint, Jasmine, Lemongrass',
        baseNotes: 'Cane Sugar, White Musk',
        tags: 'Citrus, Fresh, Unisex',
      },
      {
        id: 'prod-golden-patchouli',
        name: 'Golden Patchouli',
        slug: 'golden-patchouli',
        tagline: 'Earthy golden patchouli, autumn leaves, and warm candle wax.',
        description: 'A warm, nostalgic forest scent. Aged golden patchouli leaves are dusted with dry cloves and cardamom, resting on dry oak wood, warm candle wax, and amber.',
        price: 5000,
        compareAtPrice: 6000,
        imageUrls: JSON.stringify(['/images/golden_patchouli.jpg']),
        stock: 35,
        isFeatured: 0,
        topNotes: 'Cardamom, Clove, Orange Peel',
        heartNotes: 'Golden Patchouli, Warm Wax, Dry Leaves',
        baseNotes: 'Oak Wood, Amber, Vetiver',
        tags: 'Woody, Earthy, Amber, Unisex',
      },
      {
        id: 'prod-cuir-violette',
        name: 'Cuir Violette',
        slug: 'cuir-violette',
        tagline: 'Powdery violet blossom, dark suede, and dry wood.',
        description: 'An elegant floral-leather contrast. Sweet, powdery violet flower sits against a rugged backdrop of dark, smoky suede leather.',
        price: 5200,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/inhale.jpg']),
        stock: 30,
        isFeatured: 0,
        topNotes: 'Violet Flower, Saffron',
        heartNotes: 'Suede, Orris Root, Jasmine',
        baseNotes: 'Atlas Cedarwood, Tobacco, Amber',
        tags: 'Floral, Leather, Unisex',
      },
      {
        id: 'prod-morning-dew',
        name: 'Morning Dew',
        slug: 'morning-dew',
        tagline: 'Wet forest moss, mountain rock, and crisp morning sun dewdrops.',
        description: 'A crisp, crystalline botanical scent. Dewdrops on green forest moss and damp lichen rest on a warm, sun-warmed stone base, surrounded by fresh mountain air.',
        price: 4600,
        compareAtPrice: null,
        imageUrls: JSON.stringify(['/images/morning_dew.jpg']),
        stock: 40,
        isFeatured: 0,
        topNotes: 'Bergamot, Lime Peel, Morning Dew Accord',
        heartNotes: 'Wet Moss, Lichen, Green Ivy',
        baseNotes: 'Sandalwood, White Musk, Patchouli',
        tags: 'Fresh, Green, Unisex',
      }
    ];

    // Seed Products and Variants
    for (const prod of perfumesData) {
      await db.insert(products).values({
        id: prod.id,
        name: prod.name,
        slug: prod.slug,
        tagline: prod.tagline,
        description: prod.description,
        price: prod.price,
        compareAtPrice: prod.compareAtPrice,
        imageUrls: prod.imageUrls,
        stock: prod.stock,
        isFeatured: prod.isFeatured,
        topNotes: prod.topNotes,
        heartNotes: prod.heartNotes,
        baseNotes: prod.baseNotes,
        tags: prod.tags,
        createdAt: Math.floor(Date.now() / 1000),
      });

      // Seeding variants for each individual perfume (except the trio bundle itself which is fixed at 3x50ml)
      if (prod.id !== 'prod-discovery-trio') {
        // 30ml variant
        await db.insert(variants).values({
          id: `var-${prod.slug}-30`,
          productId: prod.id,
          size: '30ml',
          price: Math.floor(prod.price * 0.75), // 25% discount for smaller size
          stock: Math.floor(prod.stock * 0.6),
        });

        // 50ml variant (Default size matching product base price)
        await db.insert(variants).values({
          id: `var-${prod.slug}-50`,
          productId: prod.id,
          size: '50ml',
          price: prod.price,
          stock: prod.stock,
        });

        // 100ml variant
        await db.insert(variants).values({
          id: `var-${prod.slug}-100`,
          productId: prod.id,
          size: '100ml',
          price: Math.floor(prod.price * 1.65), // cheaper per ml
          stock: Math.floor(prod.stock * 0.4),
        });
      } else {
        // Trio Bundle variant
        await db.insert(variants).values({
          id: 'var-discovery-trio-3x50ml',
          productId: prod.id,
          size: '3 x 50ml',
          price: prod.price,
          stock: prod.stock,
        });
      }
    }

    return NextResponse.json({ success: true, message: 'Database successfully re-seeded with 35 luxury perfumes, variants, and admin user.' });
  } catch (e: any) {
    console.error('Seeding failed:', e);
    return NextResponse.json({ success: false, error: e.message }, { status: 500 });
  }
}
